// SPDX-FileCopyrightText: 2024 UnionTech Software Technology Co., Ltd.
//
// SPDX-License-Identifier: GPL-3.0-or-later

package version

// Automatically generated by Makefile. DO NOT EDIT.
const VERSION = "1.0.0"
